---
- name: Install Docker Configuration, Deploy Infisical
  hosts: all

  # vars:
    # postgres_password: "{{ postgres_password }}"
    # site_url: "{{ infisical_site_url }}"
    # infisical_smtp_host: "{{ infisical_smtp_host }}"
    # infisical_smtp_port: "{{ infisical_smtp_port }}"
    # infisical_smtp_from_address: "{{ infisical_smtp_from_address }}"
    # infisical_smtp_from_name: "{{ infisical_smtp_from_name }}"
    # infisical_smtp_username: "{{ infisical_smtp_username }}"
    # infisical_smtp_password: "{{ infisical_smtp_password }}"
    # infisical_persistent_volume: "{{ infisical_persistent_volume }}"

  become: true
  become_user: root

  tasks:
    - name: Install Docker
      ansible.builtin.include_tasks:
        file: "tasks/install_docker.yml"    

    - name: Install Infisical
      ansible.builtin.include_tasks:
        file: "tasks/install_infisical.yml"
