---
- name: Install Docker Configuration, Deploy Infisical
  hosts: all

  # vars:
    # All of the required variables are passed into the Ansible Playbook
    # through extra_vars in the Terraform module.

  become: true
  become_user: root

  tasks:
    - name: Install Docker
      ansible.builtin.include_tasks:
        file: "tasks/install_docker.yml"

    - name: Install Infisical
      ansible.builtin.include_tasks:
        file: "tasks/install_infisical.yml"
